import Head from 'next/head'
import {wrapper} from "@/app/store/store";
import {PER_PAGE} from "@/shared/ui/Pagination/config";
import * as api from '@/shared/api'
import Header from "@/widgets/Header";
import {ApartmentsListProps} from "@/pages-flat/types";
import ApartmentsListPage from "@/pages-flat/apartments-list";
import Alert from "@/shared/ui/Alert/Alert";
import {GetStaticPropsContext} from "next";
import {AnyAction} from "redux";
import {RootState} from "@/app/store/types";
import {Store} from "@reduxjs/toolkit";
import {serverSideTranslations} from 'next-i18next/serverSideTranslations'


export default function Home({...props}: ApartmentsListProps ) {
    return (
        <>
            <Head>
                <title>Купить квартиру в Турции!</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <Alert/>
            <main>
                <Header/>
                <ApartmentsListPage {...props} />
            </main>
        </>
    )
}

export type GetStaticPropsContextType = {store: Store<RootState, AnyAction> } & GetStaticPropsContext

export const getStaticProps = wrapper.getStaticProps(async (ctx:GetStaticPropsContextType) => {
    try {
        const payload = await api.apartments.getApartments({limit: PER_PAGE, page: 1})
        if (payload.apartments.length && ctx?.locale) {
            return {
                props: {
                    ...(await serverSideTranslations(ctx.locale, ['common'])),
                    ...payload,
                    currentPage: 1,
                }
            };
        }
    } catch (err) {
    }

    return {props: {}};
});






